*CRIAÇÃO DAS TABELEAS*

-- Tabela UNIDADE
CREATE TABLE UNIDADE (
    CNPJ NUMBER(14) PRIMARY KEY,
    ENDERECO VARCHAR2(80),
    CONTATO NUMBER(12)
);

-- Tabela PACIENTE
CREATE TABLE PACIENTE (
    IDPACIENTE NUMBER(10) PRIMARY KEY,
    CPF NUMBER(12),
    NOME VARCHAR2(40),
    DTNASCIMENTO DATE,
    EMAIL VARCHAR2(30),
    TELEFONE NUMBER(12)
);

-- Tabela UNI_PACIENTE
CREATE TABLE UNI_PACIENTE (
    CNPJ NUMBER(14),
    IDPACIENTE NUMBER(10),
    PRIMARY KEY (CNPJ, IDPACIENTE),
    FOREIGN KEY (CNPJ) REFERENCES UNIDADE(CNPJ),
    FOREIGN KEY (IDPACIENTE) REFERENCES PACIENTE(IDPACIENTE)
);

-- Tabela MEDICO
CREATE TABLE MEDICO (
    IDMEDICO NUMBER(10) PRIMARY KEY,
    CRM NUMBER(10),
    NOME VARCHAR2(40)
);

-- Tabela CONSULTA
CREATE TABLE CONSULTA (
    IDPACIENTE NUMBER(10),
    IDMEDICO NUMBER(10),
    DATA DATE,
    HORA VARCHAR2 (8),
    PRIMARY KEY (IDPACIENTE, IDMEDICO),
    FOREIGN KEY (IDPACIENTE) REFERENCES PACIENTE(IDPACIENTE),
    FOREIGN KEY (IDMEDICO) REFERENCES MEDICO(IDMEDICO)
);

-- Tabela ESPECIALIDADE
CREATE TABLE ESPECIALIDADE (
    IDESPECIALIDADE NUMBER(10) PRIMARY KEY,
    DESCRICAO VARCHAR2(30)
);

-- Tabela MED_ESPECIALIDADE 
CREATE TABLE MED_ESPECIALIDADE (
    IDMEDICO NUMBER(10),
    IDESPECIALIDADE NUMBER(10),
    PRIMARY KEY (IDMEDICO, IDESPECIALIDADE),
    FOREIGN KEY (IDMEDICO) REFERENCES MEDICO(IDMEDICO),
    FOREIGN KEY (IDESPECIALIDADE) REFERENCES ESPECIALIDADE(IDESPECIALIDADE)
);
